### ISSUE TITLE
feature request: chords for left-handed

### ISSUE THREAD

**Issue by ginolhac** [ezgraphs/ggguitar#1]
Hi,

great package! Neat idea. Would be great to reverse the strings so one can generate chords for left-handed guitars.
For example C is:

    0-3-2-0-1-0

could be left-oriented

    0-1-0-2-3-0

Cheers

**Comment by ezgraphs** [comment]
Possible using: 

```
G_M <- c(3, 2, 0, 0, 0, 3)
ggguitar::tablature('G Major', rev(G_M), x_labels = c(1,2,3,4,5,6))
```

Will update the vignette to include an example.

**Comment by ginolhac** [comment]
thanks a lot!
